export { Navbar } from './Navbar/Navbar'
export { Header} from './Header/Header'
export { Peliculas } from './Peliculas/Peliculas'
export { InfoPelicula } from './InfoPelicula/InfoPelicula'
export { ImageBox } from './ImageBox/ImageBox'
export { NotFound } from './NotFound/NotFound'